name: C/C++ CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: sudo make install
      run: sudo make install
    - name: test run
      run: porter -d
    - name: test kill
      run: porter -k
